### ISSUE TITLE
Run time error in first simluation page.

### ISSUE THREAD

**Issue by chrismainey** [hsma-programme/Teaching_DES_Concepts_Streamlit#19]
I get a runtime error when running the simulation with default settings on page:  https://hsma-programme.github.io/Teaching_DES_Concepts_Streamlit/Simulating_Arrivals.
Assume this is a classic python dependencies thing, as error is:  

RuntimeError: The pyarrow package must be version 11.0.0 or greater. Found version 0.0.1
Traceback:

**Comment by Bergam0t** [comment]
Hi @chrismainey,
Apologies for not spotting this sooner! 
This may now be fixed - I've made quite a lot of changes to the structure and dependencies. 
Would you be able to try running it again now?
 https://hsma-programme.github.io/Teaching_DES_Concepts_Streamlit/Simulating_Arrivals
If it still gives you the same error, would you be able to let me know what browser and operating system you are on, please?

**Comment by chrismainey** [comment]
Hi @Bergam0t , thank you for picking it up.  Looks good to me, all working nicely.  Lovely work by the way.  Teaches very clearly and functions well, but the presentation if it is excellent!  I particularly loved the icons! Shall I close, or will you?

**Comment by Bergam0t** [comment]
Thank you for checking it out again to confirm that's sorted now! Thank you for the lovely feedback too. I shall close this as fixed :)
